Repository thoth-station/performance, pull requests merged in 2019-07, with the labels that each got.

#12 Increase repetitions for matmul
  tensorflow/matmul.py
Labels: approved, size/XS

#14 Add basic configuration for GitHub issues and CODEOWNERS
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: approved, size/M

#13 Document performance indicator JSON structure and link to models
  README.rst
Labels: approved, size/L

#15 Rename matmul to PiMatmul to match model
  tensorflow/matmul.py
Labels: approved, size/XS

#16 Correct_matmul
  tensorflow/matmul.py
Labels: approved, size/XS

#18 Update README file with matmul performance results
  README.rst
Labels: approved, size/L, size/S

#19 Conv Thoth Performance Indicator(PI)
  tensorflow/conv.py
Labels: approved, size/L

#20 Extended PI for conv
  tensorflow/conv1d.py
  tensorflow/conv2d.py
Labels: approved, size/L

#21 Standardize name PI for Dgraph syncs
  tensorflow/conv1d.py
  tensorflow/conv2d.py
Labels: approved, size/XS
